[versions]
asciidoctorj = "2.5.8"
commons-lang3 = "3.13.0"
japicmp-plugin = "0.4.1"
gradle-custom-userdata-plugin = "1.11.1"
gradle-enterprise-plugin = "3.13.2"
gradle-github-actions-plugin = "1.3.2"
grails-gdoc = "1.0.1"
mockserver = "5.15.0"
nexus-publish-plugin = "1.3.0"
snakeyaml = "2.0"
sonar-plugin = "4.0.0.2929"
spock = "2.1-groovy-3.0"
spotless-plugin = "6.20.0"
testlogger-plugin = "3.2.0"
tomlj = "1.1.0"
typesafe-config = "1.4.2"
bytebuddy = "1.14.4"
objenesis = "3.3"

[libraries]
asciidoctorj = { module = "org.asciidoctor:asciidoctorj", version.ref = "asciidoctorj" }
bytebuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
japicmp-plugin = { module = "me.champeau.gradle:japicmp-gradle-plugin", version.ref = "japicmp-plugin" }
gradle-custom-userdata-plugin = { module = "com.gradle:common-custom-user-data-gradle-plugin", version.ref = "gradle-custom-userdata-plugin" }
gradle-enterprise-plugin = { module = "com.gradle:gradle-enterprise-gradle-plugin", version.ref = "gradle-enterprise-plugin" }
gradle-github-actions-plugin = { module = "org.nosphere.gradle.github:gradle-github-actions-plugin", version.ref = "gradle-github-actions-plugin" }
grails-gdoc = { module = "org.grails:grails-gdoc-engine", version.ref = "grails-gdoc" }
nexus-publish-plugin = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexus-publish-plugin" }
mockserver-netty = { module = "org.mock-server:mockserver-netty", version.ref = "mockserver" }
mockserver-client = { module = "org.mock-server:mockserver-client-java", version.ref = "mockserver" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
sonar-plugin = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version.ref = "sonar-plugin" }
spock-bom = { module = "org.spockframework:spock-bom", version.ref = "spock" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless-plugin" }
testlogger-plugin = { module = "com.adarshr:gradle-test-logger-plugin", version.ref = "testlogger-plugin" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }
typesafe-config = { module = "com.typesafe:config", version.ref = "typesafe-config" }
objenesis = { module = "org.objenesis:objenesis", version.ref = "objenesis" }
